"""followers

Revision ID: 225e2f6a00a7
Revises: e8342a3cf1ea
Create Date: 2025-11-07 15:42:07.715260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '225e2f6a00a7'
down_revision = 'e8342a3cf1ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('about_me',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=140),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('about_me',
               existing_type=sa.String(length=140),
               type_=sa.VARCHAR(length=64),
               nullable=False)

    op.drop_table('followers')
    # ### end Alembic commands ###
